import "./globals.css";
import type { Metadata } from "next";
import Navbar from "../components/Navbar";
import Sidbartest from "@/components/Sidbartest";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='fa'>
      <body className={""} dir='rtl'>
        <Navbar />
        <Sidbartest>{children}</Sidbartest>
      </body>
    </html>
  );
}
